insert into Users values (1,'Russell','Walker',7,123,'Stockholm');
insert into Users values (2,'Howard','Henderson ',18,123,'Remote');
insert into Users values (3,'Wayne','James',8,123,'Malmö');
insert into Users values (4,'Steven','Turner',9,123,'Stockholm');
insert into Users values (5,'Pamela ','Reed',11,123,'Stockholm');
insert into Users values (6,'Carl','James',18,123,'Göteborg');
insert into Users values (7,'Kimberly','Henderson ',9,123,'Malmö');
insert into Users values (8,'Kimberly','James',8,123,'Malmö');
insert into Users values (9,'Victor','Reed',12,123,'Malmö');
insert into Users values (10,'Wayne','James',1,123,'Malmö');
insert into Users values (11,'Rebecca','Cooper',7,123,'Stockholm');
insert into Users values (12,'Russell','Reed',3,123,'Remote');
insert into Users values (13,'Kimberly','Reed',13,123,'Malmö');
insert into Users values (14,'Victor','Walker',5,123,'Stockholm');
insert into Users values (15,'Kimberly','Walker',16,123,'Malmö');
insert into Users values (16,'Howard','Reed',0,123,'Göteborg');
insert into Users values (17,'Steven','Jones',12,123,'Stockholm');
insert into Users values (18,'Rebecca','Reed',1,123,'Remote');
insert into Users values (19,'Wayne','Jones',11,123,'Malmö');