insert into Issues values (1,'People can not hear me in Skype',1,606,'Skype','Stockholm');
insert into Issues values (2,'My Drivers will not install',11,1059,'Driver','Malmö');
insert into Issues values (3,'Can not connect to internet',1,498,'internet','Malmö');
insert into Issues values (4,'My Drivers will not install',4,1681,'Driver','Malmö');
insert into Issues values (5,'Can not connect to internet',6,2454,'internet','Remote');
insert into Issues values (6,'People can not hear me in Skype',1,784,'Skype','Stockholm');
insert into Issues values (7,'I get blue screens frequently',13,2141,'Blue screen','Remote');
insert into Issues values (8,'Can not connect to internet',2,1278,'internet','Remote');
insert into Issues values (9,'I get blue screens frequently',4,484,'Blue screen','Malmö');
insert into Issues values (10,'I get blue screens frequently',4,662,'Blue screen','Stockholm');
insert into Issues values (11,'Can not connect to internet',6,1428,'internet','Göteborg');
insert into Issues values (12,'My Drivers will not install',5,1569,'Driver','Stockholm');
insert into Issues values (13,'Can not connect to internet',3,2259,'internet','Malmö');
insert into Issues values (14,'My Drivers will not install',8,885,'Driver','Remote');
insert into Issues values (15,'Can not connect to internet',9,433,'internet','Malmö');
insert into Issues values (16,'People can not hear me in Skype',5,1916,'Skype','Göteborg');
insert into Issues values (17,'I get blue screens frequently',8,525,'Blue screen','Göteborg');
insert into Issues values (18,'My Drivers will not install',18,1379,'Driver','Remote');
insert into Issues values (19,'People can not hear me in Skype',16,408,'Skype','Remote');
insert into Issues values (20,'People can not hear me in Skype',18,2456,'Skype','Stockholm');
insert into Issues values (21,'My Drivers will not install',14,2288,'Driver','Remote');
insert into Issues values (22,'I get blue screens frequently',1,1001,'Blue screen','Remote');
insert into Issues values (23,'Can not connect to internet',18,1603,'internet','Malmö');
insert into Issues values (24,'I get blue screens frequently',6,417,'Blue screen','Remote');
insert into Issues values (25,'Can not connect to internet',18,1174,'internet','Göteborg');
insert into Issues values (26,'I get blue screens frequently',4,1825,'Blue screen','Remote');
insert into Issues values (27,'I get blue screens frequently',3,2486,'Blue screen','Göteborg');
insert into Issues values (28,'People can not hear me in Skype',8,1083,'Skype','Stockholm');
insert into Issues values (29,'I get blue screens frequently',11,1271,'Blue screen','Stockholm');
insert into Issues values (30,'I get blue screens frequently',1,466,'Blue screen','Stockholm');
insert into Issues values (31,'Can not connect to internet',16,785,'internet','Remote');
insert into Issues values (32,'People can not hear me in Skype',15,1165,'Skype','Stockholm');
insert into Issues values (33,'I get blue screens frequently',18,347,'Blue screen','Malmö');
insert into Issues values (34,'Can not connect to internet',5,541,'internet','Göteborg');
insert into Issues values (35,'I get blue screens frequently',5,2001,'Blue screen','Remote');
insert into Issues values (36,'People can not hear me in Skype',8,1640,'Skype','Remote');
insert into Issues values (37,'Can not connect to internet',1,2373,'internet','Göteborg');
insert into Issues values (38,'Can not connect to internet',7,1349,'internet','Malmö');
insert into Issues values (39,'Can not connect to internet',3,1083,'internet','Malmö');
insert into Issues values (40,'People can not hear me in Skype',16,330,'Skype','Malmö');
insert into Issues values (41,'I get blue screens frequently',9,2203,'Blue screen','Göteborg');
insert into Issues values (42,'Can not connect to internet',2,1903,'internet','Stockholm');
insert into Issues values (43,'People can not hear me in Skype',14,1074,'Skype','Stockholm');
insert into Issues values (44,'People can not hear me in Skype',6,2353,'Skype','Stockholm');
insert into Issues values (45,'My Drivers will not install',1,2422,'Driver','Remote');
insert into Issues values (46,'Can not connect to internet',3,1149,'internet','Malmö');
insert into Issues values (47,'Can not connect to internet',15,574,'internet','Stockholm');
insert into Issues values (48,'Can not connect to internet',3,1343,'internet','Malmö');
insert into Issues values (49,'People can not hear me in Skype',4,2120,'Skype','Remote');
insert into Issues values (50,'My Drivers will not install',9,1532,'Driver','Göteborg');
insert into Issues values (51,'Can not connect to internet',18,1487,'internet','Stockholm');
insert into Issues values (52,'People can not hear me in Skype',12,1766,'Skype','Malmö');
insert into Issues values (53,'My Drivers will not install',18,1245,'Driver','Remote');
insert into Issues values (54,'I get blue screens frequently',18,1272,'Blue screen','Malmö');
insert into Issues values (55,'My Drivers will not install',13,1124,'Driver','Remote');
insert into Issues values (56,'My Drivers will not install',11,2100,'Driver','Malmö');
insert into Issues values (57,'People can not hear me in Skype',8,1115,'Skype','Stockholm');
insert into Issues values (58,'People can not hear me in Skype',11,1632,'Skype','Stockholm');
insert into Issues values (59,'My Drivers will not install',14,1301,'Driver','Stockholm');
insert into Issues values (60,'I get blue screens frequently',11,2258,'Blue screen','Göteborg');
insert into Issues values (61,'I get blue screens frequently',16,1709,'Blue screen','Remote');
insert into Issues values (62,'I get blue screens frequently',16,2000,'Blue screen','Göteborg');
insert into Issues values (63,'People can not hear me in Skype',10,260,'Skype','Göteborg');
insert into Issues values (64,'I get blue screens frequently',6,2483,'Blue screen','Remote');
insert into Issues values (65,'My Drivers will not install',10,880,'Driver','Remote');
insert into Issues values (66,'My Drivers will not install',16,1540,'Driver','Remote');
insert into Issues values (67,'My Drivers will not install',18,2298,'Driver','Stockholm');
insert into Issues values (68,'People can not hear me in Skype',16,1185,'Skype','Stockholm');
insert into Issues values (69,'Can not connect to internet',16,2180,'internet','Malmö');
insert into Issues values (70,'People can not hear me in Skype',4,270,'Skype','Malmö');
insert into Issues values (71,'Can not connect to internet',9,1984,'internet','Göteborg');
insert into Issues values (72,'I get blue screens frequently',2,516,'Blue screen','Göteborg');
insert into Issues values (73,'People can not hear me in Skype',1,655,'Skype','Göteborg');
insert into Issues values (74,'People can not hear me in Skype',11,312,'Skype','Stockholm');
insert into Issues values (75,'People can not hear me in Skype',6,333,'Skype','Stockholm');
insert into Issues values (76,'My Drivers will not install',17,567,'Driver','Malmö');
insert into Issues values (77,'I get blue screens frequently',15,1283,'Blue screen','Remote');
insert into Issues values (78,'People can not hear me in Skype',3,706,'Skype','Stockholm');
insert into Issues values (79,'I get blue screens frequently',3,1100,'Blue screen','Göteborg');
insert into Issues values (80,'I get blue screens frequently',17,1283,'Blue screen','Remote');
insert into Issues values (81,'People can not hear me in Skype',1,2183,'Skype','Malmö');
insert into Issues values (82,'Can not connect to internet',12,1708,'internet','Göteborg');
insert into Issues values (83,'People can not hear me in Skype',16,899,'Skype','Malmö');
insert into Issues values (84,'My Drivers will not install',10,2364,'Driver','Remote');
insert into Issues values (85,'My Drivers will not install',3,767,'Driver','Stockholm');
insert into Issues values (86,'I get blue screens frequently',3,650,'Blue screen','Göteborg');
insert into Issues values (87,'My Drivers will not install',9,2412,'Driver','Malmö');
insert into Issues values (88,'People can not hear me in Skype',9,1631,'Skype','Remote');
insert into Issues values (89,'Can not connect to internet',1,1120,'internet','Malmö');
insert into Issues values (90,'I get blue screens frequently',17,1774,'Blue screen','Remote');
insert into Issues values (91,'Can not connect to internet',10,2302,'internet','Remote');
insert into Issues values (92,'My Drivers will not install',16,908,'Driver','Malmö');
insert into Issues values (93,'I get blue screens frequently',17,2372,'Blue screen','Remote');
insert into Issues values (94,'I get blue screens frequently',17,516,'Blue screen','Göteborg');
insert into Issues values (95,'My Drivers will not install',10,479,'Driver','Malmö');
insert into Issues values (96,'People can not hear me in Skype',14,1272,'Skype','Göteborg');
insert into Issues values (97,'Can not connect to internet',5,773,'internet','Remote');
insert into Issues values (98,'People can not hear me in Skype',6,608,'Skype','Remote');
insert into Issues values (99,'Can not connect to internet',1,502,'internet','Stockholm');
insert into Issues values (100,'People can not hear me in Skype',16,646,'Skype','Remote');
insert into Issues values (101,'I get blue screens frequently',4,1212,'Blue screen','Remote');
insert into Issues values (102,'Can not connect to internet',17,414,'internet','Göteborg');
insert into Issues values (103,'I get blue screens frequently',18,1422,'Blue screen','Malmö');
insert into Issues values (104,'Can not connect to internet',14,837,'internet','Malmö');
insert into Issues values (105,'Can not connect to internet',16,1991,'internet','Remote');
insert into Issues values (106,'My Drivers will not install',9,1031,'Driver','Göteborg');
insert into Issues values (107,'I get blue screens frequently',16,2374,'Blue screen','Göteborg');
insert into Issues values (108,'My Drivers will not install',6,2375,'Driver','Malmö');
insert into Issues values (109,'I get blue screens frequently',7,1287,'Blue screen','Stockholm');
insert into Issues values (110,'Can not connect to internet',8,704,'internet','Stockholm');
insert into Issues values (111,'Can not connect to internet',11,1668,'internet','Remote');
insert into Issues values (112,'People can not hear me in Skype',17,251,'Skype','Malmö');
insert into Issues values (113,'My Drivers will not install',1,1343,'Driver','Göteborg');
insert into Issues values (114,'Can not connect to internet',15,2139,'internet','Remote');
insert into Issues values (115,'My Drivers will not install',15,290,'Driver','Malmö');
insert into Issues values (116,'My Drivers will not install',12,1524,'Driver','Malmö');
insert into Issues values (117,'My Drivers will not install',15,1563,'Driver','Malmö');
insert into Issues values (118,'Can not connect to internet',2,1386,'internet','Stockholm');
insert into Issues values (119,'My Drivers will not install',14,2351,'Driver','Göteborg');
insert into Issues values (120,'I get blue screens frequently',9,1517,'Blue screen','Malmö');
insert into Issues values (121,'I get blue screens frequently',10,1132,'Blue screen','Malmö');
insert into Issues values (122,'I get blue screens frequently',16,951,'Blue screen','Malmö');
insert into Issues values (123,'My Drivers will not install',1,379,'Driver','Göteborg');
insert into Issues values (124,'Can not connect to internet',14,2031,'internet','Stockholm');
insert into Issues values (125,'Can not connect to internet',6,1638,'internet','Malmö');
insert into Issues values (126,'I get blue screens frequently',15,2203,'Blue screen','Stockholm');
insert into Issues values (127,'My Drivers will not install',3,494,'Driver','Stockholm');
insert into Issues values (128,'Can not connect to internet',2,992,'internet','Malmö');
insert into Issues values (129,'Can not connect to internet',9,997,'internet','Remote');
insert into Issues values (130,'Can not connect to internet',1,834,'internet','Remote');
insert into Issues values (131,'People can not hear me in Skype',6,1056,'Skype','Stockholm');
insert into Issues values (132,'People can not hear me in Skype',5,1818,'Skype','Malmö');
insert into Issues values (133,'I get blue screens frequently',13,1313,'Blue screen','Malmö');
insert into Issues values (134,'My Drivers will not install',16,2299,'Driver','Malmö');
insert into Issues values (135,'I get blue screens frequently',18,1986,'Blue screen','Göteborg');
insert into Issues values (136,'My Drivers will not install',4,536,'Driver','Malmö');
insert into Issues values (137,'Can not connect to internet',17,1873,'internet','Göteborg');
insert into Issues values (138,'I get blue screens frequently',11,1820,'Blue screen','Stockholm');
insert into Issues values (139,'I get blue screens frequently',14,2239,'Blue screen','Remote');
insert into Issues values (140,'People can not hear me in Skype',16,548,'Skype','Stockholm');
insert into Issues values (141,'People can not hear me in Skype',9,2275,'Skype','Stockholm');
insert into Issues values (142,'People can not hear me in Skype',1,338,'Skype','Göteborg');
insert into Issues values (143,'Can not connect to internet',11,906,'internet','Göteborg');
insert into Issues values (144,'People can not hear me in Skype',16,2054,'Skype','Remote');
insert into Issues values (145,'Can not connect to internet',4,342,'internet','Remote');
insert into Issues values (146,'People can not hear me in Skype',1,2379,'Skype','Göteborg');
insert into Issues values (147,'Can not connect to internet',14,2460,'internet','Malmö');
insert into Issues values (148,'People can not hear me in Skype',3,2491,'Skype','Malmö');
insert into Issues values (149,'My Drivers will not install',15,1889,'Driver','Malmö');